Update Bedrock modules for LangChain v0.3.x
explodinggradients/ragas pull request #1487
Opened 2024-10-14 07:33 UTC by minorun365

Updating LangChain modules for Amazon Bedrock (AWS) in "customizations" section.

- Use `langchain_aws` instead of `langchain_community.`
- Use `ChatBedrock` instead of `BedrockChat`

2024-10-14 11:02 UTC, shahules786 requested changes
Hey @minorun365 , thanks for this. Would you nice if you can make this change in this [file](https://github.com/explodinggradients/ragas/blob/main/docs/extra/components/choose_evaluvator_llm.md) too which is used in several docs to switch to AWS

2024-10-14 15:10 UTC, minorun365 commented
> Hey @minorun365 , thanks for this. Would you nice if you can make this change in this [file](https://github.com/explodinggradients/ragas/blob/main/docs/extra/components/choose_evaluvator_llm.md) too which is used in several docs to switch to AWS

@shahules786 Of course! Along with that, I've also updated `ChatBedrock` to the even more recent `ChatBedrockConverse`.

2024-10-15 06:30 UTC, jjmachan approved these changes
LG from my end!
thanks alot @minorun365 for helping us improve the docs 🙂 ❤️

2024-10-15 06:30 UTC, shahules786 approved these changes
LGTM. Thanks bro :)

2024-10-15 06:31 UTC, merged