feat: make general purpose metrics more general
explodinggradients/ragas pull request #1666
Opened 2024-11-13 06:10 UTC by jjmachan

a few different examples

```py
from ragas.metrics import AspectCritic
from ragas.dataset_schema import SingleTurnSample

only_response = SingleTurnSample(
    response="The Eiffel Tower is located in Paris."
)

grammar_critic = AspectCritic(
    name="grammar",
    definition="Is the response grammatically correct?",
    llm=evaluator_llm
)

await grammar_critic.single_turn_ascore(only_response)
```

with reference
```py
answer_correctness_critic = AspectCritic(
    name="answer_correctness",
    definition="Is the response and reference answer are the same?",
    llm=evaluator_llm
)

# data row
sample = SingleTurnSample(
    user_input="Where is the Eiffel Tower located?",
    response="The Eiffel Tower is located in Paris.",
    reference="London"
)
await answer_correctness_critic.single_turn_ascore(sample)
```

2024-11-14 08:20 UTC, shahules786 commented
Let's say I am evaluating using an evaluation dataset that contains user_input, response, reference, and retrieved_context. Consider scenarios of the user using two metrics with this dataset, ie context_recall and aspect critic (as harmfulness or something)  at the same time. Using this interface, even if my aspect critic metric does not need retrieved context it will use it. There is no way to opt-out.  @jjmachan

2024-11-14 12:24 UTC, shahules786 requested changes
Reflect changes in docs.

2024-11-19 11:06 UTC, jjmachan commented on docs/concepts/metrics/available_metrics/general_purpose.md
updated the docs here

2024-11-19 11:21 UTC, shahules786 commented on src/ragas/metrics/_aspect_critic.py
>      criteria: str = Field(description="The criteria to evaluate the response")
We discussed that both here and with simple criteria this should be removed. If not with this PR, I can make another PR after this is merged.

2024-11-19 11:21 UTC, shahules786 approved these changes

2024-11-19 12:21 UTC, merged