added prompt objects to metrics
explodinggradients/ragas pull request #401
Opened 2023-12-21 07:07 UTC by tinomaxthayil

* Added prompt objects to metrics

2023-12-21 07:13 UTC, tinomaxthayil commented
@shahules786 faithfulness and critique prompts are left

2023-12-25 13:17 UTC, shahules786 commented
I have raised PR to your branch. @tinomaxthayil

2023-12-28 03:30 UTC, shahules786 requested changes

2023-12-28 04:16 UTC, tinomaxthayil commented on src/ragas/metrics/_answer_relevance.py
> +QUESTION_GEN = Prompt(
You want to change this to 1/0?

2023-12-28 06:43 UTC, shahules786 commented on src/ragas/metrics/_answer_relevance.py
> +QUESTION_GEN = Prompt(
Yes

2023-12-29 04:28 UTC, shahules786 approved these changes

2023-12-31 02:41 UTC, jjmachan approved these changes

2023-12-31 04:44 UTC, merged