feat(integrations): add support for langchain and langsmith
explodinggradients/ragas pull request #795
Opened 2024-03-22 04:36 UTC by jjmachan

2024-03-27 17:11 UTC, hinthornw commented
@jjmachan happy to help if there's anything blocking this release! Would love to land so we can share more broadly (https://github.com/langchain-ai/langsmith-cookbook/blob/main/testing-examples/ragas/ragas.ipynb)

2024-03-28 15:47 UTC, mspronesti requested changes

2024-03-28 15:47 UTC, mspronesti commented on src/ragas/metrics/base.py
> +
```suggestion
ignore_columns = ignore_columns or []
```

2024-03-28 15:49 UTC, mspronesti commented on src/ragas/metrics/base.py
> +    eval_mod: EvaluationMode, ignore_columns: t.List[str] = []
```suggestion
    eval_mod: EvaluationMode, ignore_columns: t.Oprional[t.List[str]] = None
```

2024-03-28 15:51 UTC, jjmachan commented
thanks for the catch @mspronesti 🙌🏽 

ps: will add docs soon but feel free to look at https://notes.explodinggradients.com/en/latest/RAG-Experiments/basecamp-handbook/baseline-langchain.html for how to use this in action, I'll docs in the mean time

2024-03-28 15:55 UTC, mspronesti commented
@jjmachan I accidentally misspelled `Optional` with an "r" 😅

2024-03-28 15:57 UTC, jjmachan commented
no worries - I missed it but at least our linters caught it 😂

2024-03-28 16:01 UTC, merged