reproducibility PR2: add new statement creation
explodinggradients/ragas pull request #930
Opened 2024-05-02 20:49 UTC by shahules786

2024-05-02 23:56 UTC, jjmachan commented
add discriptions to your PRs - only for once you request review!

2024-05-02 23:58 UTC, jjmachan requested changes
lets get PR1 merged first before this
this feels like it has commits from both?

2024-05-03 00:24 UTC, shahules786 commented
@jjmachan you're right. PR2 is to be merged after PR1. I cut a branch from PR1 because changes to be made was depended on each other.

2024-05-03 20:07 UTC, jjmachan approved these changes
I think the last PR neads to be rebased for this to merge?

2024-05-03 20:07 UTC, jjmachan commented on src/ragas/metrics/base.py
> +ensembler = Ensember()
why is ensembler a class instead of a function?

2024-05-08 02:10 UTC, closed without merging