Improve JSON format prompt for large chunks & Handle ZeroDivisionError
explodinggradients/ragas pull request #982
Opened 2024-05-21 14:02 UTC by Manav916

## Description
In this PR there are three different changes
## Changes

1. Fixed a Typo in the filter_question_prompt Instruction from `Asses` to `Assess`
2. Added a try-except block for handling ZeroDivisionError for the filter method in the NodeFilter class
3. Improved the JSON_FORMAT_INSTRUCTIONS for better output generation
It seems like the LLM sometimes loses track of the imposed instruction for the output, especially for long prompts. So although the output generated for a chunk_size of 512 is perfect, the output for a chunk_size of 1024 has an extra newline. Here parsing fails when using PydanticOutputParser even though the llm has generated an output and there is only an extra `'\n'`. 
![image](https://github.com/explodinggradients/ragas/assets/77217074/e29e314c-dbb6-45aa-acc3-08ad1940a476)
But by tuning the prompt and adding `Please output your response in the demanded json format.` at the end of the instruction we get output without `'\n'`. This output can then be parsed and the context can be considered.

2024-05-22 12:17 UTC, jjmachan commented
@shahules786 could you check if we can merge this in?

2024-05-24 11:46 UTC, mspronesti requested changes

2024-05-24 11:46 UTC, mspronesti commented on src/ragas/testset/filters.py
> +            output["score"] = 0  # or some default value or handling
Relying on exceptions for control flow is usually not efficient. Just use a third operator:

```suggestion
        vals = output.values()
        output["score"] = sum(vals) / n_vals if (n_vals := len(vals)) > 0 else 0
```

2024-11-03 04:56 UTC, jjmachan commented
hey @Manav916 we did make some improvements with the v0.2 release - do check it out

closing this for now but I'm really sorry we couldn't merge it 🙁 but at the same time thanks a million for taking the time to raise this, really grateful too and do checkout this form https://docs.google.com/forms/d/e/1FAIpQLSdM9FrrZrnpByG4XxuTbcAB-zn-Z7i_a7CsMkgBVOWQjRJckg/viewform - our way of saying thank you 🙂

2024-11-03 04:56 UTC, closed without merging